#!/bin/bash

subject="$2"

echo -e "hash for: '$subject'\n"

function sha256() {
  echo -n "$subject" | openssl sha256 -binary
}

function sha384() {
  echo -n "$subject" | openssl sha384 -binary
}

function sha512() {
  echo -n "$subject" | openssl sha512 -binary
}

function __base64() {
  openssl base64
}

case "$1" in
  sha256) sha256 | __base64;;
  sha384) sha384 | __base64;;
  sha512) sha512 | __base64;;
  *) echo "unknown arg '${1}'";;
esac
